api:
    resource: "@APIBundle/Resources/config/routing.yml"
    prefix:   /V0.11/

# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation

# NelmioApiDocBundle:
#     resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#     prefix:   /api/doc
