
send_file:
    path:     /cloud/sendFile
    defaults: { _controller: AppBundle:Cloud:sendFileAction }

open_secured_stream:
    path:     /cloud/openstream
    defaults: { _controller: AppBundle:Cloud:openStreamAction }

close_stream:
    path:     /cloud/closestream
    defaults: { _controller: AppBundle:Cloud:openUnsecuredStreamAction }



list_files_and_directories:
    path:     /cloud/ls
    defaults: { _controller: AppBundle:Cloud:listFilesAndDirectories }
