SQLBundle\Entity\Gantt:
    type: entity
    table: gantts
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        updatedAt:
            type: datetime
            column: updated_at
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        projects:
          targetEntity: Project
          inversedBy: gantts
          joinColumn:
            name: project_id
            referencedColumnName: id
            nullable: TRUE
        creator_user:
          targetEntity: User
          inveredBy: gantt_creator
          joinColumn:
            name: creator_id
            referencedColumnName: id
        updator_user:
          targetEntity: User
          inveredBy: gantt_updator
          joinColumn:
            name: updator_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
