SQLBundle\Entity\Newsletter:
    type: entity
    table: newsletter
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
          type: string
          length: 255
          nullable: FALSE
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
    lifecycleCallbacks: {  }