SQLBundle\Entity\Notification:
    type: entity
    table: notifications
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            column: type
        targetId:
            type: integer
            column: target_id
        message:
            type: text
        createdAt:
            type: datetime
            column: created_at
        isRead:
            type: boolean
            column: isRead
    manyToOne:
            user:
              targetEntity: User
              inversedBy: notifications
              joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
