SQLBundle\Entity\StatBugsUsersRepartition:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: integer
        percentage:
            type: float
    manyToOne:
        project:
          targetEntity: Project
          inversedBy: StatBugsUsersRepartition
          joinColumn:
            name: project_id
            referencedColumnName: id
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
