SQLBundle\Entity\StatUserWorkingCharge:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        charge:
            type: integer
    manyToOne:
        project:
          targetEntity: Project
          inversedBy: StatUserWorkingCharge
          joinColumn:
            name: project_id
            referencedColumnName: id
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
