SQLBundle\Entity\StatLateTasks:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        role:
            type: string
            length: 255
        lateTasks:
            type: integer
        ontimeTasks:
            type: integer
    manyToOne:
        project:
          targetEntity: Project
          inversedBy: StatLateTasks
          joinColumn:
            name: project_id
            referencedColumnName: id
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
