SQLBundle\Entity\StatProjectAdvancement:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        percentage:
            type: smallint
        progress:
            type: smallint
        totalTasks:
            type: integer
        finishedTasks:
            type: integer
        date:
            type: datetime
    manyToOne:
        project:
          targetEntity: Project
          inversedBy: StatProjectAdvancement
          joinColumn:
            name: project_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
