SQLBundle\Entity\TimelineType:
    type: entity
    table: timeline_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
