SQLBundle\Entity\WhiteboardModif:
    type: entity
    table: whiteboard_modifs
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        whiteboardId:
            type: integer
            column: whiteboard_id
        drawType:
            type: smallint
            column: draw_type
        path:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
