language: php
php:
  - 5.6
sudo: required
services:
  - mysql
before_install:
  - pecl install --force mongo | echo "no"
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - cd API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh
script:
  - php -m