language: php
php:
  - '5.6'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
    packages:
      - apache2
install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get -y install php5.6 php5.6-dev php5.6-mongo php5.6-intl
before_script:
  - sudo pecl install mongo
  - sudo phpenv config-add myconfig.ini
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh