language: android
jdk:
  - oraclejdk8
before_script:
  - cd ./Grappbox
  -- "android update sdk --no-ui --filter build-tools-24.0.1,android-24,extra-android-m2repository"
after_script:
  - cd ..
  - git update-index --chmod=+x ./Grappbox/gradlew && ./Grappbox/gradlew build && ./Grappbox/gradlew test && ./Grappbox/gradlew cAT

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86_64-android-22
