language: php
php:
  - 5.6
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - mysql
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd API
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php composer.phar self-update
  - php composer.phar install
  - php app/console doctrine:generate:entities SQLBundle
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
script:
  - bin/phpunit --debug -c app