language: php
php:
  - '5.6'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
before_script:
  - sudo wget http://pear.php.net/go-pear.phar
  - sudo php go-pear.phar
  - sudo pecl install mongo
  - sudo phpenv config-add myconfig.ini
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh