language: php
php:
  - 7.0
sudo: required
dist: trusty
services:
  - mysql
before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd API
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php composer.phar self-update
  - php composer.phar install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:generate:entities SQLBundle
  - php bin/console doctrine:schema:create --env=test
  - mysql -p -u root < INSERT INTO `symfony.timeline_types` (`id`, `name`) VALUES (NULL, 'customerTimeline')(NULL, 'teamTimeline')
script:
  - phpunit --debug