language: php
php:
  - '5.6'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
before_install:
  - echo "extension=mongo.so"  >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh