language: php
php:
  - '7.0'
sudo: required
services:
  - mysql
before_script:
  - sudo apt-get install php-pear
  - sudo pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - cd API
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh