language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
script:
  - cd ./Web
  - chmod +x composer.prod.sh
  - ./composer.prod.sh
