language: php
php:
  - '5.6'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
    packages:
      - apache2
      - libapache2-mod-fastcgi
install:
  - sudo add-apt-repository -y ppa:ondrej/php; sudo apt-get -qq update; fi
  - sudo apt-get -y install php5.6 php5.6-dev libapache2-mod-php5.6 apache2-threaded-dev php5.6php.net/-pear php5.6-mongo php5.6-intl; fi
before_script:
  - sudo phpenv config-add myconfig.ini
  - sudo pecl install mongo
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh