language: php
php:
  - '7.0'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
services:
  - mysql
before_script:
  - composer self-update
  - phpenv config-add myconfig.ini
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh