language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
before_script:
  - phpenv config-add myconfig.ini
  - pecl install -f mongo-1.3.0
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - ./composer.prod.sh
