language: php
php:
  - 5.6
sudo: required
services:
  - mysql
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - cd API
  - composer -n --no-ansi install --prefer-source
script:
  - php app/check.php