language: php
php:
  - '7.0'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
services:
  - mysql
before_install: echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh