language: php
php:
  - 7.0
sudo: required
services:
  - mysql
before_install:
  - pecl install --force mongodb
before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - cd API
  - composer -n --no-ansi install --dev --prefer-source
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh