language: php
php:
  - 7.0
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server
    - mysql-client-core
    - mysql-client
services:
  - mysql
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd API
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php composer.phar self-update
  - php composer.phar install
  - php app/console doctrine:generate:entities SQLBundle
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
script:
  - phpunit --debug -c app