language: php
php:
  - '5.6'
env:
  global:
    - SYMFONY_ENV=prod
sudo: required
before_script:
  - sudo add-apt-repository main
  - sudo add-apt-repository universe
  - sudo add-apt-repository restricted
  - sudo add-apt-repository multiverse
  - sudo apt-get update -qq
  - sudo apt-get install php5.6-dev php5.6php.net/-pear php5.6-mongo php5.6-intl
  - sudo phpenv config-add myconfig.ini
  - sudo pecl install mongo
script:
  - cd ./API
  - chmod +x composer.prod.sh
  - sudo ./composer.prod.sh