home_index:
    path:     /
    defaults: { _controller: HomeBundle:Home:index }

home_resource:
    path: /{url}
    defaults: { _controller: HomeBundle:Home:removeTailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
