<?php

namespace Proxies\__CG__\SQLBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \SQLBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'lastname', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'birthday', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'avatar', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'avatarDate', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'country', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'linkedin', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'viadeo', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'twitter', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'isClient', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'bug_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'message_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'event_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'project_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_updator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_user', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'gantt_updator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'notifications', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'devices', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'task_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'colors', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'ressources', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'authentications', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'projects', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'events'];
        }

        return ['__isInitialized__', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'lastname', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'birthday', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'avatar', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'avatarDate', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'country', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'linkedin', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'viadeo', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'twitter', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'isClient', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'bug_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'message_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'event_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'project_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_updator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'whiteboard_user', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'gantt_updator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'notifications', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'devices', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'task_creator', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'colors', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'ressources', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'authentications', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'projects', '' . "\0" . 'SQLBundle\\Entity\\User' . "\0" . 'events'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function fullObjectToArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fullObjectToArray', []);

        return parent::fullObjectToArray();
    }

    /**
     * {@inheritDoc}
     */
    public function objectToArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'objectToArray', []);

        return parent::objectToArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$avatar]);

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatarDate($avatarDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatarDate', [$avatarDate]);

        return parent::setAvatarDate($avatarDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatarDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatarDate', []);

        return parent::getAvatarDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedin($linkedin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', [$linkedin]);

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', []);

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setViadeo($viadeo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViadeo', [$viadeo]);

        return parent::setViadeo($viadeo);
    }

    /**
     * {@inheritDoc}
     */
    public function getViadeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViadeo', []);

        return parent::getViadeo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', [$twitter]);

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', []);

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsClient($isClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsClient', [$isClient]);

        return parent::setIsClient($isClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsClient', []);

        return parent::getIsClient();
    }

    /**
     * {@inheritDoc}
     */
    public function addBugCreator(\SQLBundle\Entity\Bug $bugCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBugCreator', [$bugCreator]);

        return parent::addBugCreator($bugCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBugCreator(\SQLBundle\Entity\Bug $bugCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBugCreator', [$bugCreator]);

        return parent::removeBugCreator($bugCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getBugCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBugCreator', []);

        return parent::getBugCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessageCreator(\SQLBundle\Entity\TimelineMessage $messageCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessageCreator', [$messageCreator]);

        return parent::addMessageCreator($messageCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessageCreator(\SQLBundle\Entity\TimelineMessage $messageCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessageCreator', [$messageCreator]);

        return parent::removeMessageCreator($messageCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageCreator', []);

        return parent::getMessageCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addEventCreator(\SQLBundle\Entity\Event $eventCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEventCreator', [$eventCreator]);

        return parent::addEventCreator($eventCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEventCreator(\SQLBundle\Entity\Event $eventCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEventCreator', [$eventCreator]);

        return parent::removeEventCreator($eventCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCreator', []);

        return parent::getEventCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjectCreator(\SQLBundle\Entity\Project $projectCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjectCreator', [$projectCreator]);

        return parent::addProjectCreator($projectCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjectCreator(\SQLBundle\Entity\Project $projectCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjectCreator', [$projectCreator]);

        return parent::removeProjectCreator($projectCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectCreator', []);

        return parent::getProjectCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addWhiteboardCreator(\SQLBundle\Entity\Whiteboard $whiteboardCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWhiteboardCreator', [$whiteboardCreator]);

        return parent::addWhiteboardCreator($whiteboardCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWhiteboardCreator(\SQLBundle\Entity\Whiteboard $whiteboardCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWhiteboardCreator', [$whiteboardCreator]);

        return parent::removeWhiteboardCreator($whiteboardCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhiteboardCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhiteboardCreator', []);

        return parent::getWhiteboardCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addWhiteboardUpdator(\SQLBundle\Entity\Whiteboard $whiteboardUpdator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWhiteboardUpdator', [$whiteboardUpdator]);

        return parent::addWhiteboardUpdator($whiteboardUpdator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWhiteboardUpdator(\SQLBundle\Entity\Whiteboard $whiteboardUpdator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWhiteboardUpdator', [$whiteboardUpdator]);

        return parent::removeWhiteboardUpdator($whiteboardUpdator);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhiteboardUpdator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhiteboardUpdator', []);

        return parent::getWhiteboardUpdator();
    }

    /**
     * {@inheritDoc}
     */
    public function addWhiteboardUser(\SQLBundle\Entity\WhiteboardPerson $whiteboardUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWhiteboardUser', [$whiteboardUser]);

        return parent::addWhiteboardUser($whiteboardUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWhiteboardUser(\SQLBundle\Entity\WhiteboardPerson $whiteboardUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWhiteboardUser', [$whiteboardUser]);

        return parent::removeWhiteboardUser($whiteboardUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getWhiteboardUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhiteboardUser', []);

        return parent::getWhiteboardUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addGanttUpdator(\SQLBundle\Entity\Gantt $ganttUpdator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGanttUpdator', [$ganttUpdator]);

        return parent::addGanttUpdator($ganttUpdator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGanttUpdator(\SQLBundle\Entity\Gantt $ganttUpdator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGanttUpdator', [$ganttUpdator]);

        return parent::removeGanttUpdator($ganttUpdator);
    }

    /**
     * {@inheritDoc}
     */
    public function getGanttUpdator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGanttUpdator', []);

        return parent::getGanttUpdator();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotification(\SQLBundle\Entity\Notification $notifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotification', [$notifications]);

        return parent::addNotification($notifications);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotification(\SQLBundle\Entity\Notification $notifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotification', [$notifications]);

        return parent::removeNotification($notifications);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotifications', []);

        return parent::getNotifications();
    }

    /**
     * {@inheritDoc}
     */
    public function addDevice(\SQLBundle\Entity\Devices $devices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDevice', [$devices]);

        return parent::addDevice($devices);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDevice(\SQLBundle\Entity\Devices $devices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDevice', [$devices]);

        return parent::removeDevice($devices);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevices', []);

        return parent::getDevices();
    }

    /**
     * {@inheritDoc}
     */
    public function addTaskCreator(\SQLBundle\Entity\Task $taskCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTaskCreator', [$taskCreator]);

        return parent::addTaskCreator($taskCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTaskCreator(\SQLBundle\Entity\Task $taskCreator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTaskCreator', [$taskCreator]);

        return parent::removeTaskCreator($taskCreator);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaskCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaskCreator', []);

        return parent::getTaskCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addColor(\SQLBundle\Entity\Color $colors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addColor', [$colors]);

        return parent::addColor($colors);
    }

    /**
     * {@inheritDoc}
     */
    public function removeColor(\SQLBundle\Entity\Color $colors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeColor', [$colors]);

        return parent::removeColor($colors);
    }

    /**
     * {@inheritDoc}
     */
    public function getColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColors', []);

        return parent::getColors();
    }

    /**
     * {@inheritDoc}
     */
    public function addRessource(\SQLBundle\Entity\Ressources $ressources)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRessource', [$ressources]);

        return parent::addRessource($ressources);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRessource(\SQLBundle\Entity\Ressources $ressources)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRessource', [$ressources]);

        return parent::removeRessource($ressources);
    }

    /**
     * {@inheritDoc}
     */
    public function getRessources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRessources', []);

        return parent::getRessources();
    }

    /**
     * {@inheritDoc}
     */
    public function addAuthentication(\SQLBundle\Entity\Authentication $authentications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAuthentication', [$authentications]);

        return parent::addAuthentication($authentications);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAuthentication(\SQLBundle\Entity\Authentication $authentications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAuthentication', [$authentications]);

        return parent::removeAuthentication($authentications);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthentications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthentications', []);

        return parent::getAuthentications();
    }

    /**
     * {@inheritDoc}
     */
    public function addProject(\SQLBundle\Entity\Project $projects)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProject', [$projects]);

        return parent::addProject($projects);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProject(\SQLBundle\Entity\Project $projects)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProject', [$projects]);

        return parent::removeProject($projects);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjects', []);

        return parent::getProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent(\SQLBundle\Entity\Event $events)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent', [$events]);

        return parent::addEvent($events);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvent(\SQLBundle\Entity\Event $events)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvent', [$events]);

        return parent::removeEvent($events);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', []);

        return parent::getEvents();
    }

}
