app_home:
    path: /
    defaults: { _controller: AppBundle:Home:index }

app_login:
    path: /login
    defaults: { _controller: AppBundle:Login:index }

app_register:
    path: /register
    defaults: { _controller: AppBundle:Register:index }

app_index:
    path: /app/
    defaults: { _controller: AppBundle:App:index }

app_routing:
    path: /app/{url}
    defaults: { _controller: AppBundle:App:rewrite }

app_routing_advanced:
    path: /app/{url}/{parameters}
    defaults: { _controller: AppBundle:App:rewrite }
    requirements:
      parameters: ".+"

app_resource:
    path: /{url}
    defaults: { _controller: AppBundle:Home:rewrite }
    requirements:
        url: .*/$
    methods: [GET]
