grappbox_app_home:
    path: /
    defaults: { _controller: AppBundle:Home:index }

grappbox_app_login:
    path: /login
    defaults: { _controller: AppBundle:Login:index }

# grappbox_app_register:
#     path: /register
#     defaults: { _controller: AppBundle:Register:index }

grappbox_app_customer_register:
    path: /register/customer
    defaults: { _controller: AppBundle:RegisterCustomer:index }

grappbox_app_preorder:
    path: /register
    defaults: { _controller: AppBundle:Preorder:index }

grappbox_app_index:
    path: /app/
    defaults: { _controller: AppBundle:App:index }

grappbox_app_routing:
    path: /app/{url}
    defaults: { _controller: AppBundle:App:rewrite }

grappbox_app_routing_advanced:
    path: /app/{url}/{parameters}
    defaults: { _controller: AppBundle:App:rewrite }
    requirements:
      parameters: ".+"

grappbox_app_resource:
    path: /{url}
    defaults: { _controller: AppBundle:Home:rewrite }
    requirements:
        url: .*/$
    methods: [GET]
