app_home:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_routing:
    path: /{url}
    defaults: { _controller: AppBundle:App:index_setAngularRouteManagement }

app_routing_advanced:
    path: /{url}/{parameters}
    defaults: { _controller: AppBundle:App:index_setAngularRouteManagement }
    requirements:
      parameters: ".+"
