app_home:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_angular:
    path: /{url}
    defaults: { _controller: AppBundle:AppRouting:angularRouteManagement }

app_angular_advanced:
    path: /{url}/{parameters}
    defaults: { _controller: AppBundle:AppRouting:angularRouteManagement }
    requirements:
      parameters: ".+"
