app_home:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_angular_routing:
    path: /{url}
    defaults: { _controller: AppBundle:AppRouting:enableAngularRouteManagement }

app_angular_routing_with_parameters:
    path: /{url}/{parameters}
    defaults: { _controller: AppBundle:AppRouting:enableAngularRouteManagement }
    requirements:
      parameters: ".+"
