app_dashboard:
    resource: "@AppDashboardBundle/Resources/config/routing.yml"
    prefix:   /app

showcase_home:
    resource: "@ShowcaseHomeBundle/Resources/config/routing.yml"
    prefix:   /

#app_shared:
#    resource: "@AppSharedBundle/Resources/config/routing.yml"
#    prefix:   /

#showcase_shared:
#    resource: "@ShowcaseSharedBundle/Resources/config/routing.yml"
#    prefix:   /