GrappboxBundle\Entity\Contains:
    type: entity
    table: contains
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
      title:
        type: string
        length: 255
      beginDate:
        type: datetime
        column: begin_date
        nullable: TRUE
      endDate:
        type: datetime
        column: end_date
        nullable: TRUE
      projectID:
        column: project_id
        type: integer
    oneToMany:
        tasks:
          targetEntity: Task
          mappedBy: contains
          cascade: [refresh]