APIBundle\Entity\Project:
    type: entity
    repositoryClass: APIBundle\Entity\ProjectRepository
    table: projects
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        logo:
            type: text
            nullable: TRUE
        phone:
            type: string
            nullable: true
        company:
            type: string
            nullable: true
        contactEmail:
            type: string
            length: 255
            column: contact_email
            nullable: TRUE
        facebook:
            type: string
            length: 255
            nullable: TRUE
        twitter:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
        safePassword:
            type: string
            column: safe_password
            nullable: TRUE
    manyToMany:
        users:
          targetEntity: User
          inversedBy: projects
          joinTable:
            name: team_project
            joinColumns:
              project_id:
                referencedColumnName: id
            inverseJoinColumns:
              user_id:
                referencedColumnName: id
    manyToOne:
        creator_user:
          targetEntity: User
          inversedBy: project_creator
          joinColumn:
            name: creator_id
            referencedColumnName: id
    oneToMany:
        tasks:
          targetEntity: Task
          mappedBy: projects
          cascade: [remove]
        bugs:
          targetEntity: Bug
          mappedBy: projects
          cascade: [remove]
        timelines:
          targetEntity: Timeline
          mappedBy: projects
          cascade: [remove]
        events:
          targetEntity: Event
          mappedBy: projects
          cascade: [remove]
        whiteboards:
          targetEntity: Whiteboard
          mappedBy: projects
          cascade: [remove]
        roles:
          targetEntity: Role
          mappedBy: projects
          cascade: [remove]
        gantts:
          targetEntity: Gantt
          mappedBy: projects
          cascade: [remove]
        customers_access:
          targetEntity: CustomerAccess
          mappedBy: projects
          cascade: [remove]
        tags:
          targetEntity: Tag
          mappedBy: project
          cascade: [remove]
    lifecycleCallbacks: {  }
