GrappboxBundle\Entity\StatBugsEvolution:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        createdBugs:
            type: integer
        closedBugs:
            type: integer
    manyToOne:
        project:
          targetEntity: Project
          inversedBy: StatBugsEvolution
          joinColumn:
            name: project_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
