MongoBundle\Document\StatBugsUsersRepartition:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        user:
            type: string
            length: 255
        value:
            type: int
        percentage:
            type: float
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: statBugsUsersRepartition
    lifecycleCallbacks: {  }
