GrappboxBundle\Entity\Task:
    type: entity
    repositoryClass: GrappboxBundle\Entity\TaskRepository
    table: tasks
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creatorId:
            type: integer
            column: creator_id
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        dueDate:
            type: datetime
            column: due_date
            nullable: TRUE
        startedAt:
            type: datetime
            column: started_at
        finishedAt:
            type: datetime
            column: finished_at
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
    manyToOne:
        projects:
          targetEntity: Project
          inversedBy: tasks
          joinColumn:
            name: project_id
            referencedColumnName: id
    manyToMany:
        users:
          targetEntity: User
          inversedBy: tasks
          joinTable:
            name: task_users
            joinColumns:
              task_id:
                referencedColumnName: id
            inverseJoinColumns:
              user_id:
                referencedColumnName: id
        tags:
          targetEntity: Tag
          inversedBy: tasks
          joinTable:
            name: task_tags
            joinColumns:
              task_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
