GrappboxBundle\Entity\Timeline:
    type: entity
    table: timeline
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeId:
            type: integer
            column: type_id
        projectId:
            type: integer
            column: project_id
        name:
            type: string
            length: 255
    manyToOne:
        projects:
          targetEntity: Project
          inversedBy: timelines
          joinColumn:
            name: project_id
            referencedColumnName: id
    oneToMany:
        timelineMessages:
          targetEntity: TimelineMessage
          mappedBy: timelines
          cascade: [remove]
    lifecycleCallbacks: {  }
