GrappboxBundle\Entity\EventType:
    type: entity
    table: event_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        events:
          targetEntity: Event
          mappedBy: events
    lifecycleCallbacks: {  }
