<?php

namespace GrappboxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findUserByName($firstname, $lastname)
	{
		$qb = $this->createQueryBuilder('u')->where('u.firstname = :firstname', 'u.lastname = :lastname')->setParameter('firstname', $firstname)->setParameter('lastname', $lastname);

		$users = $qb->getQuery()->getResult();

		$arr = array();
		$i = 1;

		foreach ($users as $user) {
			$id = $user->getId();

			$arr["User ".$i] = array("id" => $id, "first_name" => $firstname, "last_name" => $lastname);
		}

		return $arr;
	}
}
