# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  service_cloud:
    class: SQLBundle\Controller\CloudController
    calls:
            - [setContainer, ["@service_container"]]
  service_stat:
    class: SQLBundle\Controller\StatisticController
    calls:
            - [setContainer, ["@service_container"]]
  service_notifs:
    class: SQLBundle\Controller\NotificationController
    calls:
            - [setContainer, ["@service_container"]]
  mongo_service_cloud:
    class: MongoBundle\Controller\CloudController
    calls:
            - [setContainer, ["@service_container"]]
  mongo_service_stat:
    class: MongoBundle\Controller\StatisticController
    calls:
            - [setContainer, ["@service_container"]]
  mongo_service_notifs:
    class: MongoBundle\Controller\NotificationController
    calls:
            - [setContainer, ["@service_container"]]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
