showcase_home:
    path:     /
    defaults: { _controller: ShowcaseBundle:Home:index }

showcase_resource_slash:
    path: /{url}
    defaults: { _controller: ShowcaseBundle:Resource:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
