APIBundle\Entity\Bug:
    type: entity
    table: bugs
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creatorId:
            type: integer
            column: creator_id
        # userId:
        #     type: integer
        #     column: user_id
        #     nullable: TRUE
        parentId:
            type: integer
            column: parent_id
            nullable: TRUE
        projectId:
            type: integer
            column: project_id
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        stateId:
            type: integer
            column: state_id
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        editedAt:
            type: datetime
            column: edited_at
            nullable: TRUE
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
    manyToOne:
        projects:
          targetEntity: Project
          inversedBy: bugs
          joinColumn:
            name: project_id
            referencedColumnName: id
    manyToMany:
        users:
          targetEntity: User
          inversedBy: bugs
          joinTable:
            name: bugs_user
            joinColumns:
              bug_id:
                referencedColumnName: id
            inverseJoinColumns:
              user_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
