APIBundle\Entity\BugTag:
    type: entity
    table: bug_tags
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bugId:
            type: integer
            column: bug_id
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
