APIBundle\Entity\Document:
    type: entity
    table: documents
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creatorId:
            type: integer
            column: creator_id
        path:
            type: string
            length: 255
        hash:
            type: string
            length: 255
    lifecycleCallbacks: {  }
