APIBundle\Entity\Gantt:
    type: entity
    table: gantts
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        projectId:
            type: integer
            column: project_id
        creatorId:
            type: integer
            column: creator_id
        updatorId:
            type: integer
            column: updator_id
        updatedAt:
            type: datetime
            column: updated_at
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
