APIBundle\Entity\Project:
    type: entity
    repositoryClass: APIBundle\Entity\ProjectRepository
    table: projects
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creatorId:
            type: integer
            column: creator_id
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        logo:
            type: string
            length: 255
            nullable: TRUE
        teamId:
            type: integer
            column: team_id
            nullable: TRUE
        contactEmail:
            type: string
            length: 255
            column: contact_email
            nullable: TRUE
        facebook:
            type: string
            length: 255
            nullable: TRUE
        twitter:
            type: string
            length: 255
            nullable: TRUE
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
        safePassword:
            type: string
            column: safe_password
            nullable: FALSE
    manyToMany:
        users:
          targetEntity: User
          inversedBy: projects
          joinTable:
            name: team_project
            joinColumns:
              project_id:
                referencedColumnName: id
            inverseJoinColumns:
              user_id:
                referencedColumnName: id
    oneToMany:
        tasks:
          targetEntity: Task
          mappedBy: projects
        bugs:
          targetEntity: Bug
          mappedBy: projects
        timelines:
          targetEntity: Timeline
          mappedBy: projects
        events:
          targetEntity: Event
          mappedBy: projects
        whiteboards:
          targetEntity: Whiteboard
          mappedBy: projects
    lifecycleCallbacks: {  }
