APIBundle\Entity\Setting:
    type: entity
    table: settings
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        bugAlert:
            type: smallint
            column: bug_alert
        eventAlert:
            type: smallint
            column: event_alert
        assignAlert:
            type: smallint
            column: assign_alert
        lateAlert:
            type: smallint
            column: late_alert
        alertFrequency:
            type: smallint
            column: alert_frequency
    lifecycleCallbacks: {  }
