APIBundle\Entity\Task:
    type: entity
    table: tasks
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        projectId:
            type: integer
            column: project_id
        creatorId:
            type: integer
            column: creator_id
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        dueDate:
            type: datetime
            column: due_date
            nullable: TRUE
        startedAt:
            type: datetime
            column: started_at
        finishedAt:
            type: datetime
            column: finished_at
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
    manyToOne:
        users:
          targetEntity: User
          inversedBy: tasks
          joinColumn:
            name: user_id
            referencedColumnName: id
        projects:
          targetEntity: Project
          inversedBy: tasks
          joinColumn:
            name: project_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
