APIBundle\Entity\TimelineMessage:
    type: entity
    table: timeline_messages
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        timelineId:
            type: integer
            column: timeline_id
        message:
            type: text
        parentId:
            type: integer
            column: parent_id
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: TRUE
        editedAt:
            type: datetime
            column: edited_at
            nullable: TRUE
    manyToOne:
        timelines:
          targetEntity: Timeline
          inversedBy: timelineMessages
          joinColumn:
            name: timeline_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
