APIBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        birthday:
            type: datetime
            nullable: TRUE
        avatar:
            type: string
            length: 255
            nullable: TRUE
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        phone:
            type: string
            length: 255
            nullable: TRUE
        country:
            type: string
            length: 255
            nullable: TRUE
        linkedin:
            type: string
            length: 255
            nullable: TRUE
        viadeo:
            type: string
            length: 255
            nullable: TRUE
        twitter:
            type: string
            length: 255
            nullable: TRUE
        isActive:
          type: boolean
        token:
          type: string
          length: 255
          nullable: TRUE
    manyToMany:
        projects:
          targetEntity: Project
          mappedBy: users
    oneToMany:
        tasks:
          targetEntity: Task
          mappedBy: users
        # whiteboards:
        #   targetEntity: Whiteboard
        #   mappedBy: updators
    lifecycleCallbacks: {  }
