MongoBundle\Document\Bug:
    type: document
    db: symfony_database
    collection: bugs
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        title:
            type: string
            length: 255
        description:
            type: string
            nullable: TRUE
        state:
            type: boolean
        createdAt:
            type: date
            name: created_at
        editedAt:
            type: date
            name: edited_at
            nullable: TRUE
        clientOrigin:
            type: boolean
            name: client_origin
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: bugs
        creator:
          targetDocument: User
          inversedBy: bug_creator
    referenceMany:
        users:
          targetDocument: User
          inversedBy: bugs
        bugtracker_tags:
          targetDocument: BugtrackerTag
          inversedBy: bugs
        comments:
          targetDocument: BugComment
          inversedBy: bugs
    lifecycleCallbacks: {  }
