MongoBundle\Document\Event:
    type: document
    db: symfony_database
    collection: events
    repositoryClass: MongoBundle\Document\EventRepository
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        title:
            type: string
            length: 255
        description:
            type: string
            nullable: TRUE
        icon:
            type: text
            nullalbe: TRUE
        beginDate:
            type: date
            name: begin_date
        endDate:
            type: date
            name: end_date
        createdAt:
            type: date
            name: created_at
        editedAt:
            type: date
            name: edited_at
            nullable: TRUE
        deletedAt:
            type: date
            name: deleted_at
            nullable: TRUE
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: events
          nullable: TRUE
        eventtypes:
          targetDocument: EventType
          inversedBy: events
        creator_user:
          targetDocument: User
          inveredBy: event_creator
    referenceMany:
        users:
          targetDocument: User
          inversedBy: events
    lifecycleCallbacks: {  }
