MongoBundle\Document\Gantt:
    type: document
    db: symfony_database
    collection: gantts
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        updatedAt:
            type: date
            name: updated_at
        createdAt:
            type: date
            name: created_at
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: gantts
          nullable: TRUE
        creator_user:
          targetDocument: User
          inveredBy: gantt_creator
        updator_user:
          targetDocument: User
          inveredBy: gantt_updator
    lifecycleCallbacks: {  }