MongoBundle\Document\Role:
    type: document
    db: symfony_database
    collection: roles
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        name:
            type: string
            length: 255
            nullable: FALSE
        teamTimeline:
            type: int
            name: team_timeline
            nullable: FALSE
        customerTimeline:
            type: int
            name: customer_timeline
            nullable: FALSE
        gantt:
            type: int
            nullable: FALSE
        whiteboard:
            type: int
            nullable: FALSE
        bugtracker:
            type: int
            nullable: FALSE
        event:
            type: int
            nullable: FALSE
        task:
            type: int
            nullable: FALSE
        projectSettings:
            type: int
            name: project_settings
            nullable: FALSE
        cloud:
            type: int
            name: cloud
            nullable: FALSE
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: roles
    lifecycleCallbacks: {  }