MongoBundle\Document\StatUserTasksAdvancement:
    type: document
    db: symfony_database
    collection: statUserTasksAdvancement
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        tasksToDo:
            type: int
        tasksDoing:
            type: int
        tasksDone:
            type: int
        tasksLate:
            type: int
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statUserTasksAdvancement
        user:
          targetDocument: User
    lifecycleCallbacks: {  }
