MongoBundle\Document\StatBugsEvolution:
    type: document
    db: symfony_database
    collection: statBugsEvolution
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        date:
            type: date
        createdBugs:
            type: int
        closedBugs:
            type: int
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statBugsEvolution
    lifecycleCallbacks: {  }
