MongoBundle\Document\StatUserWorkingCharge:
    type: document
    db: symfony_database
    collection: statUserWorkingCharge
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        charge:
            type: int
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statUserWorkingCharge
        user:
          targetDocument: User
    lifecycleCallbacks: {  }
