MongoBundle\Document\StatTasksRepartition:
    type: document
    db: symfony_database
    collection: statTasksRepartition
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        role:
            type: string
            length: 255
        value:
            type: int
        percentage:
            type: int
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statTasksRepartition
        user:
          targetDocument: User
    lifecycleCallbacks: {  }
