MongoBundle\Document\StatBugsUsersRepartition:
    type: document
    db: symfony_database
    collection: statBugsUsersRepartition
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        value:
            type: int
        percentage:
            type: float
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statBugsUsersRepartition
        user:
          targetDocument: User
    lifecycleCallbacks: {  }
