MongoBundle\Document\Timeline:
    type: document
    db: symfony_database
    collection: timeline
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        typeId:
            type: int
            name: type_id
        projectId:
            type: string
            name: project_id
        name:
            type: string
            length: 255
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: timelines
    referenceMany:
        timelineMessages:
          targetDocument: TimelineMessage
          mappedBy: timelines
          cascade: [remove]
    lifecycleCallbacks: {  }
