MongoBundle\Document\User:
    type: document
    db: symfony_database
    collection: users
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        birthday:
            type: date
            nullable: TRUE
        avatar:
            type: string
            nullable: TRUE
        avatarDate:
            type: date
            nullable: TRUE
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: TRUE
        phone:
            type: string
            length: 255
            nullable: TRUE
        country:
            type: string
            length: 255
            nullable: TRUE
        linkedin:
            type: string
            length: 255
            nullable: TRUE
        viadeo:
            type: string
            length: 255
            nullable: TRUE
        twitter:
            type: string
            length: 255
            nullable: TRUE
        isClient:
          type: boolean
          name: is_client
    referenceMany:
        projects:
          targetDocument: Project
          inversedBy: users
        events:
          targetDocument: Event
          inversedBy: users
        bug_creator:
          targetDocument: Bug
          inversedBy: creator
        message_creator:
          targetDocument: TimelineMessage
          inversedBy: creator
        event_creator:
          targetDocument: Event
          inversedBy: creator_user
        project_creator:
          targetDocument: Project
          inversedBy: creator_user
        whiteboard_creator:
          targetDocument: Whiteboard
          inversedBy: creator_user
        whiteboard_updator:
          targetDocument: Whiteboard
          inversedBy: updator_user
        whiteboard_user:
          targetDocument: WhiteboardPerson
          inversedBy: user
        gantt_updator:
          targetDocument: Gantt
          inversedBy: updator_id
        notifications:
          targetDocument: Notification
          inversedBy: user
          cascade: [remove]
        devices:
          targetDocument: Devices
          inversedBy: user
          cascade: [remove]
        task_creator:
          targetDocument: Task
          inversedBy: creator_user
        colors:
          targetDocument: Color
          inversedBy: user
          cascade: [remove]
        ressources:
          targetDocument: Ressources
          inversedBy: user
        authentications:
          targetDocument: Authentication
          inversedBy: user
    lifecycleCallbacks: {  }
