MongoBundle\Document\Whiteboard:
    type: document
    db: symfony_database
    collection: whiteboards
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        name:
            type: string
            length: 255
        updatedAt:
            type: date
            name: updated_at
        createdAt:
            type: date
            name: created_at
        deletedAt:
            type: date
            name: deleted_at
            nullable: TRUE
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: whiteboards
        creator_user:
          targetDocument: User
          inversedBy: whiteboard_creator
        updator_user:
          targetDocument: User
          inversedBy: whiteboard_updator
    referenceMany:
        objects:
          targetDocument: WhiteboardObject
          targetDocument: whiteboard
          cascade: [remove]
        persons:
          targetDocument: WhiteboardPerson
          targetDocument: whiteboard
          cascade: [remove]
    lifecycleCallbacks: {  }
