MongoBundle\Document\CloudSecuredFileMetadata:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        filename:
            type: string
            length: 255
        password:
            type: string
        creationDate:
            type: date
            name: creation_date
        cloudPath:
            type: string
    lifecycleCallbacks: {  }