MongoBundle\Document\CloudTransfer:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        filename:
            type: string
            length: 255
        path:
            type: string
        creationDate:
            type: date
            name: creation_date
        deletionDate:
            type: date
            name: deletion_date
            nullable: TRUE
        password:
            type: string
            nullable: TRUE
        creator_id:
            type: int
            name: creator_id
    lifecycleCallbacks: {  }
