MongoBundle\Document\Color:
    type: document
    db: symfony_database
    collection: colors
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        color:
            type: string
            length: 255
    referenceOne:
        user:
          targetDocument: User
          inversedBy: colors
        project:
          targetDocument: Project
          inversedBy: colors
    lifecycleCallbacks: {  }
