MongoBundle\Document\Dependencies:
    type: document
    db: symfony_database
    collection: dependence
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        name:
            type: string
            length: 255
    referenceOne:
        dependence_task:
          targetDocument: Task
          inversedBy: task_depended
        task:
          targetDocument: Task
          inversedBy: dependence
    lifecycleCallbacks: {  }
