MongoBundle\Document\Devices:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        token:
            type: string
            length: 255
    referenceOne:
        user:
          targetDocument: User
          inversedBy: devices
    lifecycleCallbacks: {  }
