MongoBundle\Document\Ressources:
    type: document
    db: symfony_database
    collection: ressources
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        resource:
            type: int
    referenceOne:
        task:
          targetDocument: Task
          inversedBy: ressources
        user:
          targetDocument: User
          inversedBy: ressources
    lifecycleCallbacks: {  }
