MongoBundle\Document\StatBugsEvolution:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        date:
            type: date
        createBugs:
            type: int
        closedBugs:
            type: date
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: statBugsEvolution
    lifecycleCallbacks: {  }
