MongoBundle\Document\StatUserWorkingCharge:
    type: document
    db: symfony_database
    collection: null
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        user:
            type: string
            length: 255
        charge:
            type: int
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: statUserWorkingCharge
    lifecycleCallbacks: {  }
