MongoBundle\Document\StatStorageSize:
    type: document
    db: symfony_database
    collection: statStorageSize
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        value:
            type: int
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: statStorageSize
    lifecycleCallbacks: {  }
