MongoBundle\Document\StatLateTasks:
    type: document
    db: symfony_database
    collection: statLateTasks
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        date:
            type: date
        user:
            type: string
            length: 255
        role:
            type: string
            length: 255
        lateTasks:
            type: int
        ontimeTasks:
            type: int
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: statLateTasks
    lifecycleCallbacks: {  }
