MongoBundle\Document\Tag:
    type: document
    db: symfony_database
    collection: tags
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        name:
            type: string
            length: 255
    referenceMany:
        tasks:
          targetDocument: Task
          mappedBy: tags
        bugs:
          targetDocument: Bug
          mappedBy: tags
    referenceOne:
        project:
          targetDocument: Project
          inversedBy: tags
    lifecycleCallbacks: {  }
