MongoBundle\Document\Task:
    type: document
    db: symfony_database
    collection: tasks
    repositoryClass: MongoBundle\Document\TaskRepository
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        title:
            type: string
            length: 255
        description:
            type: string
            nullable: TRUE
        dueDate:
            type: date
            name: due_date
            nullable: TRUE
        startedAt:
            type: date
            name: started_at
        finishedAt:
            type: date
            name: finished_at
            nullable: TRUE
        createdAt:
            type: date
            name: created_at
        deletedAt:
            type: date
            name: deleted_at
            nullable: TRUE
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: tasks
        creator_user:
          targetDocument: User
          inveredBy: task_creator
    referenceMany:
        users:
          targetDocument: User
          inversedBy: tasks
        tags:
          targetDocument: Tag
          inversedBy: tasks
    lifecycleCallbacks: {  }