MongoBundle\Document\TimelineMessage:
    type: document
    db: symfony_database
    collection: timeline_messages
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        timelineId:
            type: int
            name: timeline_id
        title:
            type: string
            length: 255
        message:
            type: string
        parentId:
            type: int
            name: parent_id
            nullable: TRUE
        createdAt:
            type: date
            name: created_at
        deletedAt:
            type: date
            name: deleted_at
            nullable: TRUE
        editedAt:
            type: date
            name: edited_at
            nullable: TRUE
    referenceOne:
        timelines:
          targetDocument: Timeline
          inversedBy: timelineMessages
        creator:
          targetDocument: User
          inversedBy: message_creator
    lifecycleCallbacks: {  }
