MongoBundle\Document\Whiteboard:
    type: document
    db: symfony_database
    collection: whiteboards
    fields:
        id:
            type: id
            id: true
            strategy: AUTO
        userId:
           type: int
           name: user_id
        name:
            type: string
            length: 255
        updatorId:
            type: int
            name: updator_id
        updatedAt:
            type: date
            name: updated_at
        createdAt:
            type: date
            name: created_at
        deletedAt:
            type: date
            name: deleted_at
            nullable: TRUE
    referenceOne:
        projects:
          targetDocument: Project
          inversedBy: whiteboards
    referenceMany:
        objects:
          targetDocument: WhiteboardObject
          mappedBy: whiteboard
          cascade: [remove]
    lifecycleCallbacks: {  }