<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function findNextMeetings($id)
	{
		$qb = $this->createQueryBuilder('e')->join('e.eventusers', 'eu')->where('eu.userId = :id')->setParameter('id', $id);
		$meetings = $qb->getQuery()->getResult();

		$arr = array();
		$i = 0;
		$defaultDate = new \DateTime;

		foreach ($meetings as $meeting) {
			$endDate = $meeting->getEndDate();
			if ($endDate > $defaultDate)
			{
				$project = $meeting->getProjects();
				$eventType = $meeting->getEventtypes();

			 	$typeName = $eventType->getName();
				$projectName = $project->getName();
				$projectLogo = $project->getLogo();
				$eventTitle = $meeting->getTitle();
				$eventDescription = $meeting->getDescription();
				$beginDate = $meeting->getBeginDate();

				$arr["Meeting ".$i] = array("project_name" => $projectName, "project_logo" => $projectLogo, "event_type" => $typeName, "event_title" => $eventTitle,
					"event_description" => $eventDescription, "event_begin_date" => $beginDate, "event_end_date" => $endDate);
				$i++;
			}
		}
		return ($arr);
	}
}
