<?php

namespace APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserRoleRepository extends EntityRepository
{

}
