language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
sudo: required
script:
  - cd ./Grappbox/Web
  - php app/check.php
  - chmod +x ./composer.prod.sh
  - ./composer.prod.sh
